FROM apache/airflow:2.9.2
RUN pip install --no-cache-dir \
    apache-airflow-providers-snowflake==5.3.1 \
    dbt-core==1.8.7 \
    dbt-snowflake==1.8.4 \
    snowflake-connector-python==3.10.1 \
    python-dotenv